language: python
matrix:
  include:
    - sudo: required
      dist: xenial
      services: docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2
script:
  - make test
  - $PIP install cibuildwheel==0.10.2
  - cibuildwheel --output-dir wheelhouse
