language: python

matrix:
  include:
    - sudo: required
      dist: xenial
      services: docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP=*-manylinux1_i686

script:
  - make test
  - $PIP install cibuildwheel==0.10.2 twine
  - cibuildwheel --output-dir wheelhouse

